spring.application.name=sbae
server.port=8080

# Connexion à PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/incidents
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# On ne laisse pas Hibernate créer les tables (elles sont créées par le script SQL de Docker)
spring.jpa.hibernate.ddl-auto=none
# Afficher les requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI access: http://localhost:8080/swagger-ui/index.html
springdoc.api-docs.path=/api-docs

# Augmente le niveau de log pour le framework et Hibernate
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.project.sbae=INFO

# Pour voir les détails des erreurs d'initialisation des beans
logging.level.org.springframework.beans=INFO